### ISSUE TITLE
supported mail clients

### ISSUE THREAD

**Issue by krzysztofantczak** [maxvyaznikov/imapseagull#7]
Hello,

Which mail clients did You tested against this server? I'm playing around with imapseagull since  yesterday and it seems it works (partially) with thunderbird only, windows live mail almost doesn't work with it (A37 LIST "" "INBOXInbox/%" - i'm not IMAP expert but this one looks odd to me), eM Client same as WLM (or even worse). What can we do to improve this situation?

Also, how would You go with managing folders on database level so we could create/rename folders using mail client?

Kind regards,
Chris.

**Comment by maxvyaznikov** [comment]
Hello.
1. For now it was tested only with Thunderbird (works right in most cases) and MS Outlook (issue #5). 
2. I turned off folder managing to make a server with base functionality as quick as possible. Hoodiecrow, which was a base for imapseagull, supported folders renaming. But first one works only in memory and in singleuser-mode (that is why second one was created). So, if you take that realization (https://github.com/andris9/hoodiecrow/blob/master/lib/commands/rename.js), compare with code of some of commands from here (this for example, https://github.com/maxvyaznikov/imapseagull/blob/master/lib/commands/list.js), then you can see that code looks very similar. 
1. First of all, you should realize DB implementation to keep folder information for each separate user and modify hoodiecrow's rename command realization to work with it. 
2. To go away from hoodiecrow's singleuser-mode, let's look into the part of rename-command source code:
```
    try{
        connection.server.deleteMailbox(source, true);
        connection.server.createMailbox(destination, mailbox);
        connection.server.indexFolders();
    }catch(E){
```
Some of this functions was dropped in imapseagull because of useless in multiuser-mode, but can bu found into hoodiecrow (for example: https://github.com/andris9/hoodiecrow/blob/ffed1b5317b2ecfc5fb7c12466978d2587dd07b9/lib/server.js#L246). In imapseagull, I think, it should be into the IMAPConnection module (https://github.com/maxvyaznikov/imapseagull/blob/master/lib/connection.js) like indexFolders is.

**Comment by krzysztofantczak** [comment]
New command can be provided only by plugin? or is there some other special case for commands?
